FROM golang:1.22.3-alpine AS builder

WORKDIR /go/src/github.com/kenoboya/goods-service-api

COPY . .

RUN go mod download
RUN GOOS=linux go build -o ./api ./cmd/api/main.go

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /go/src/github.com/kenoboya/goods-service-api .
COPY .env .
COPY configs /configs

CMD ["./api"]